---
title: "Water Quality Test"
description: |
  A short description of the post.
author:
  - name: Gavin Gordon
    url: https://example.com/norajones
date: 01-22-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = T,message = F,warning = F)
```

```{r}
library(tidyverse)
library(SHT)
library(vroom)
library(plotly)
library(gt)
library(gtsummary)
library(Hotelling)
library(pander)
library(expss)
library(beanplot)
library(pairwiseCI)
library(heplots)
library(GGally)
library(lubridate)
```

```{r}
dataset <- vroom("C:/Users/gavin/Documents/GitHub/blogdata/portharcourtdata-bothseasons-long-19aug2016.csv")

```
```{r}

dataset <- dataset %>% mutate(year = year(Date)) %>% filter(year == 2014,treatment == "no",WaterPurposes != "cook",WaterPurposes != "cook/wash",WaterPurposes != "wash",source_type != "borehole commercial",source_type != "borehole govt",source_type != "water vendor") %>% select(Nitrate,pH,Turbidity,EC,Fluoride,TDS,source_type)


dataset <- dataset[complete.cases(dataset),]

dataset$Nitrate <- as.numeric(dataset$Nitrate)
```


```{r}
bivar <- dataset %>% ggpairs(aes(color = source_type)) + theme_bw() 
ggplotly(bivar,height = 700,width = 1200)

```