---
title: "Wine Analysis Pt2"
description: |
  A short description of the post.
author:
  - name: Gavin Gordon
    url: https://example.com/norajones
date: 02-10-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache = T,message = F,warning = F)
```

```{r}
library(tidyverse)
library(SHT)
library(vroom)
library(plotly)
library(gt)
library(gtsummary)
library(Hotelling)
library(pander)
library(expss)
library(beanplot)
library(pairwiseCI)
library(heplots)
library(GGally)
library(randomForest)
library(lubridate)
library(caret)
library(robustbase)
library(mda)
library(MASS)
library(klaR)
library(ggord)
```

```{r}
names <- c("cultivar","alcohol","malic_acid","ash","alcalinity_of_ash" ,"magnesium" , "total_phenols" ,"flavanoids", "nonflavanoid_phenols","proanthocyanins","color_intensity","hue","OD280/OD315_of_diluted_wines",
"proline") 

dataset <- vroom("C:/Users/gavin/Documents/GitHub/blogdata/wine_data.csv",col_names = names)
rm(names)
dataset$cultivar <- factor(dataset$cultivar)
#data$cultivar <- factor(data$cultivar)

```


```{r}
#Data Splitting
predictors <- dataset[2:7]
cultivar <- dataset$cultivar


# Set the random number seed so we can reproduce the results
set.seed(2020)
trainingRows <- createDataPartition(cultivar, p = .8, list= FALSE)
trainPredictors <- predictors[trainingRows, ]
traincultivar <- cultivar[trainingRows]
testPredictors <- predictors[-trainingRows, ]
testcultivar <- cultivar[-trainingRows]
traindata <- data.frame(trainPredictors,traincultivar)

```


```{r}
group1 <- filter(traindata,traincultivar == 1)
group1$outlier <- factor(covMcd(group1[,1:6],alpha = 0.5)$mcd.wt,labels = c("Outlier","Not Outlier"))

group2 <- filter(traindata,traincultivar == 2)
group2$outlier <- factor(covMcd(group2[,1:6],alpha = 0.5)$mcd.wt,labels = c("Outlier","Not Outlier"))

group3 <- filter(traindata,traincultivar == 3)
group3$outlier <- factor(covMcd(group3[,1:6],alpha = 0.5)$mcd.wt,labels = c("Outlier","Not Outlier"))

traindata <- rbind(filter(group1,outlier != "Outlier"),filter(group2,outlier != "Outlier"),filter(group3,outlier != "Outlier"))

traindata <- traindata[,1:7]

rm(group1,group2,group3)


```

```{r}
pander(leveneTests(traindata[,1:6],group = traindata$traincultivar))

```

<center>
```{r}
p <- ggpairs(data=traindata[,1:7],aes(color = traincultivar)) + theme_bw()
ggplotly(p,height = 1000,width = 1000)
```
</center>


<center>
```{r}
model <- mda(traincultivar ~ .,data = traindata )
plot(model)
predictions <- predict(model,testPredictors)
summary(model)
```
</center>

```{r}
confusion(predictions,testcultivar)
```

```{r}
model2  <- lda(traincultivar ~ . ,data = traindata)
model2
```
<center>
```{r}
prediction <- data.frame(predict(model2,testPredictors),testcultivar)
p <- ggplot(data = prediction,aes(prediction$x.LD1,color = testcultivar)) + 
  geom_density() + 
  theme_bw() + 
  labs(x = "First Discriminant Function",title = "Z Score Distribution",color = "Cultivar") + 
  theme(plot.title = element_text(hjust = 0.5))
ggplotly(p)
```
</center>


<center>
```{r}
p <- ggplot(data = prediction,aes(prediction$x.LD2,color = testcultivar)) + 
  geom_density() + 
  theme_bw() + 
  labs(x = "Second Discriminant Function",
       title = "Z Score Distribution",
       color = "Cultivars") + 
  theme(plot.title = element_text(hjust = 0.5))
ggplotly(p)
```
</center>

<center>
```{r}
p <- ggplot(data = prediction,aes(x.LD1,x.LD2,color = testcultivar)) + 
  geom_point() + 
  stat_ellipse() + 
  theme_bw() + 
  labs(x = "First Discriminant Function",
       y = "Second Discriminant Function",
       title = "Z Score Distributions",
       color = "Cultivars") + 
  theme(plot.title = element_text(hjust = 0.5))
ggplotly(p)
```
</center>



```{r}
forest <- randomForest(data = traindata, traincultivar ~ .,ntree = 10000)


confusion(predict(forest,testPredictors),testcultivar)

```
